const UPLOAD_ITEM_MODEL = "admin:UPLOAD_ITEM_MODEL";
const DELETE_ITEM_MODEL = "admin:DELETE_ITEM_MODEL";
const GET_ITEM = "user/admin:GET_ITEM";
const GET_ALL_ITEMS = "user/admin:GET_ITEM";
const EDIT_ITEM_TYPE = "admin:DELETE_ITEM_MODEL";

const CREATE_OUTFIT = "user/admin:CREATE_OUTFIT";
const EDIT_OUTFIT = "user/admin:EDIT_OUTFIT";
const GET_ALL_OUTFITS = "user/admin:GET_ALL_OUTFITS";
const GET_CURRENT_CUSTOMER_OUTFITS = "user/admin:GET_CURRENT_CUSTOMER_OUTFITS";
const SEARCH_OUTFIT = "user/admin:SEARCH_OUTFIT";

const TOGGLE_LIKE_ITEM = "user:TOGGLE_LIKE_ITEM";
const GET_CURRENT_CUSTOMER = "user:GET_CURRENT_CUSTOMER";

const ADD_AVATAR = "admin:ADD_AVATAR";
const EDIT_AVATAR = "admin:EDIT_AVATAR";
const DELETE_AVATAR = "admin:DELETE_AVATAR";
const GET_AVATAR = "admin:GET_AVATAR";
const GET_ALL_AVATARS = "admin:GET_ALL_AVATARS";

const ADD_ITEM_TO_SELECTED_ITEM_LIST = "user:ADD_ITEM_TO_SELECTED_ITEM_LIST";
const REMOVE_ITEM_FROM_SELECTED_ITEM_LIST = "user:REMOVE_ITEM_FROM_SELECTED_ITEM_LIST";
const ADD_OUTFIT_TO_SELECTED_OUTFIT_LIST = "user:ADD_OUTFIT_TO_SELECTED_OUTFIT_LIST";
const REMOVE_OUTFIT_FROM_SELECTED_OUTFIT_LIST = "user:REMOVE_OUTFIT_FROM_SELECTED_OUTFIT_LIST";
const CHANGE_AVATAR_BODY_TYPE = "user:CHANGE_AVATAR_BODY_TYPE";
const GET_CURRENT_CUSTOMER_FITTING_ROOM = "user:GET_CURRENT_CUSTOMER_FITTING_ROOM";


module.exports = {
    UPLOAD_ITEM_MODEL,
    DELETE_ITEM_MODEL,
    GET_ITEM,
    GET_ALL_ITEMS,
    EDIT_ITEM_TYPE,
    CREATE_OUTFIT,
    EDIT_OUTFIT,
    GET_ALL_OUTFITS,
    GET_CURRENT_CUSTOMER_OUTFITS,
    SEARCH_OUTFIT,
    TOGGLE_LIKE_ITEM,
    GET_CURRENT_CUSTOMER,
    ADD_AVATAR,
    EDIT_AVATAR,
    DELETE_AVATAR,
    GET_AVATAR,
    GET_ALL_AVATARS,
    ADD_ITEM_TO_SELECTED_ITEM_LIST,
    REMOVE_ITEM_FROM_SELECTED_ITEM_LIST,
    ADD_OUTFIT_TO_SELECTED_OUTFIT_LIST,
    REMOVE_OUTFIT_FROM_SELECTED_OUTFIT_LIST,
    CHANGE_AVATAR_BODY_TYPE,
    GET_CURRENT_CUSTOMER_FITTING_ROOM
}